<a href="https://colab.research.google.com/github/BitKnitting/FitHome_DeepLearning_1/blob/master/notebooks/dl_train_val_test_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction
We prepared the aggregated electricity readings and the column of 0s and 1s representing when the microwave was off or on in [this notebook](https://colab.research.google.com/github/BitKnitting/FitHome_DeepLearning_1/blob/master/notebooks/dl_process.ipynb).  Now that we have readied the data, it is time to get it into the shape that will be fed into the Keras Deep Learning Model.
## Data Shape
We will be following the data shape used in a [previous notebook](https://colab.research.google.com/github/BitKnitting/transfer_nilm_exploration/blob/master/ExploreNILM_1.ipynb)
- windows of 100 readings in time series order are fed into the model.
- The first window includes the 1st - 100th readings.  The second window includes the 2nd - 101st readings.  I.E.: A 1-reading sliding window moves along the time series feeding the model 100 readings as it slides along.
## Example 
What we need to create is an array of indexes into our data that will grab the right readings for the sliding window.  In the example below, the windowsize is 10 and the number of sample readings is 30.
- `rows` : The first index in each row.  I.e.: the 1st window starts at the first reading.  The 2nd window at the 2nd reading, etc. i.e.: the rows are the start index of each window.  Given a windowsize of 10, there are 21 windows of readings that can be fed into the model.
- `cols` : Each value in the column is an index into the readings.
- `indexer` : The array of indexes sets us up to easily pull the readings out as a 1-reading sliding window of readings.

In [9]:
import numpy as np
# @title Simple Indexer example
windowsize = 10
numberreadings = 30
# Let's set up the rows first.
# the number of rows =  numberreadings - windowsize + 1
rows = np.arange(numberreadings-windowsize+1)
print('******************* ROWS *****************************')
# Now let's get this 1D vector into a 2D Vector:
rows = rows.reshape(-1,1)
display(rows)
print(f'\nShape: {rows.shape}')
# Onto the columns
print('\n******************* COLS *****************************')
cols = np.arange(windowsize)
cols = cols.reshape(1,-1)
display(cols)
print(f'\nShape: {cols.shape}')
# Add these two vectors together
indexer = rows + cols
print('\n***************** INDEXER ***************************')
display(indexer)
print(f'\nShape: {indexer.shape}')


******************* ROWS *****************************


array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])


Shape: (21, 1)

******************* COLS *****************************


array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])


Shape: (1, 10)

***************** INDEXER ***************************


array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
       [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
       [20, 21, 22, 


Shape: (21, 10)


we have 21 windows of readings.  Each window includes windowsize (10) readings.  Each window slides the start/end of the readings one reading over until all readings are included within a window.